// Generated by protoc-gen-vala VERSION from plugin.proto, do not edit

public class CodeGeneratorRequest
{
    public List<string> file_to_generate;
    public string? parameter;
    public List<FileDescriptorProto> proto_file;

    public CodeGeneratorRequest.from_data (uint8[] buffer, size_t length, size_t offset = 0)
    {
        decode (buffer, length, offset);
    }

    public void decode (uint8[] buffer, size_t length, size_t offset = 0)
    {
        while (offset < length)
        {
            var key = Protobuf.decode_varint (buffer, length, ref offset);
            var wire_type = key & 0x7;
            var field_number = key >> 3;
            int varint;
            var value_length = Protobuf.get_value_length (wire_type, out varint, buffer, length, ref offset);
            // FIXME: Check remaining space

            switch (field_number)
            {
            case 1:
                this.file_to_generate.append (Protobuf.decode_string (buffer, offset + value_length, offset));
                break;
            case 2:
                this.parameter = Protobuf.decode_string (buffer, offset + value_length, offset);
                break;
            case 15:
                this.proto_file.append (new FileDescriptorProto.from_data (buffer, offset + value_length, offset));
                break;
            }

            offset += value_length;
        }
    }

    public size_t encode (uint8[] buffer, ref size_t offset)
    {
        var start = offset;

        for (unowned List<FileDescriptorProto> i = this.proto_file.last (); i != null; i = i.prev)
        {
            var n = i.data.encode (buffer, ref offset);
            Protobuf.encode_varint (n, buffer, ref offset);
            Protobuf.encode_varint (122, buffer, ref offset);
        }
        if (this.parameter != null)
        {
            var n = Protobuf.encode_string (this.parameter, buffer, ref offset);
            Protobuf.encode_varint (n, buffer, ref offset);
            Protobuf.encode_varint (18, buffer, ref offset);
        }
        for (unowned List<string> i = this.file_to_generate.last (); i != null; i = i.prev)
        {
            var n = Protobuf.encode_string (i.data, buffer, ref offset);
            Protobuf.encode_varint (n, buffer, ref offset);
            Protobuf.encode_varint (10, buffer, ref offset);
        }

        return start - offset;
    }

    public string to_string (string indent = "")
    {
        var text = "{\n";

        if (this.file_to_generate != null)
        {
            text += "file_to_generate = ";
            foreach (var v in this.file_to_generate)
                text += "\"%s\";\n".printf (v);
        }

        if (this.parameter != null)
        {
            text += "parameter = ";
            text += "\"%s\";\n".printf (this.parameter);
        }

        if (this.proto_file != null)
        {
            text += "proto_file = ";
            foreach (var v in this.proto_file)
                text += "%s;\n".printf (v.to_string ());
        }

        text += "}";
        return text;
    }
}

public class CodeGeneratorResponse
{
    public class File
    {
        public string? name;
        public string? insertion_point;
        public string? content;

        public File.from_data (uint8[] buffer, size_t length, size_t offset = 0)
        {
            decode (buffer, length, offset);
        }

        public void decode (uint8[] buffer, size_t length, size_t offset = 0)
        {
            while (offset < length)
            {
                var key = Protobuf.decode_varint (buffer, length, ref offset);
                var wire_type = key & 0x7;
                var field_number = key >> 3;
                int varint;
                var value_length = Protobuf.get_value_length (wire_type, out varint, buffer, length, ref offset);
                // FIXME: Check remaining space

                switch (field_number)
                {
                case 1:
                    this.name = Protobuf.decode_string (buffer, offset + value_length, offset);
                    break;
                case 2:
                    this.insertion_point = Protobuf.decode_string (buffer, offset + value_length, offset);
                    break;
                case 15:
                    this.content = Protobuf.decode_string (buffer, offset + value_length, offset);
                    break;
                }

                offset += value_length;
            }
        }

        public size_t encode (uint8[] buffer, ref size_t offset)
        {
            var start = offset;

            if (this.content != null)
            {
                var n = Protobuf.encode_string (this.content, buffer, ref offset);
                Protobuf.encode_varint (n, buffer, ref offset);
                Protobuf.encode_varint (122, buffer, ref offset);
            }
            if (this.insertion_point != null)
            {
                var n = Protobuf.encode_string (this.insertion_point, buffer, ref offset);
                Protobuf.encode_varint (n, buffer, ref offset);
                Protobuf.encode_varint (18, buffer, ref offset);
            }
            if (this.name != null)
            {
                var n = Protobuf.encode_string (this.name, buffer, ref offset);
                Protobuf.encode_varint (n, buffer, ref offset);
                Protobuf.encode_varint (10, buffer, ref offset);
            }

            return start - offset;
        }

        public string to_string (string indent = "")
        {
            var text = "{\n";

            if (this.name != null)
            {
                text += "name = ";
                text += "\"%s\";\n".printf (this.name);
            }

            if (this.insertion_point != null)
            {
                text += "insertion_point = ";
                text += "\"%s\";\n".printf (this.insertion_point);
            }

            if (this.content != null)
            {
                text += "content = ";
                text += "\"%s\";\n".printf (this.content);
            }

            text += "}";
            return text;
        }
    }
    public string? error;
    public List<File> file;

    public CodeGeneratorResponse.from_data (uint8[] buffer, size_t length, size_t offset = 0)
    {
        decode (buffer, length, offset);
    }

    public void decode (uint8[] buffer, size_t length, size_t offset = 0)
    {
        while (offset < length)
        {
            var key = Protobuf.decode_varint (buffer, length, ref offset);
            var wire_type = key & 0x7;
            var field_number = key >> 3;
            int varint;
            var value_length = Protobuf.get_value_length (wire_type, out varint, buffer, length, ref offset);
            // FIXME: Check remaining space

            switch (field_number)
            {
            case 1:
                this.error = Protobuf.decode_string (buffer, offset + value_length, offset);
                break;
            case 15:
                this.file.append (new File.from_data (buffer, offset + value_length, offset));
                break;
            }

            offset += value_length;
        }
    }

    public size_t encode (uint8[] buffer, ref size_t offset)
    {
        var start = offset;

        for (unowned List<File> i = this.file.last (); i != null; i = i.prev)
        {
            var n = i.data.encode (buffer, ref offset);
            Protobuf.encode_varint (n, buffer, ref offset);
            Protobuf.encode_varint (122, buffer, ref offset);
        }
        if (this.error != null)
        {
            var n = Protobuf.encode_string (this.error, buffer, ref offset);
            Protobuf.encode_varint (n, buffer, ref offset);
            Protobuf.encode_varint (10, buffer, ref offset);
        }

        return start - offset;
    }

    public string to_string (string indent = "")
    {
        var text = "{\n";

        if (this.error != null)
        {
            text += "error = ";
            text += "\"%s\";\n".printf (this.error);
        }

        if (this.file != null)
        {
            text += "file = ";
            foreach (var v in this.file)
                text += "%s;\n".printf (v.to_string ());
        }

        text += "}";
        return text;
    }
}
