// Generated by protoc-gen-vala 0.0.5 from google/protobuf/descriptor.proto, do not edit

public class FileDescriptorSet
{
    public List<FileDescriptorProto> file = null;

    public FileDescriptorSet.from_data (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        decode (buffer, data_length);
    }

    public void decode (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        var end = buffer.read_index + data_length;

        while (buffer.read_index < end)
        {
            var key = buffer.decode_varint ();
            var wire_type = key & 0x7;
            var field_number = key >> 3;

            if (field_number == 1 && wire_type == 2)
                this.file.append (new FileDescriptorProto.from_data (buffer, (size_t) buffer.decode_varint ()));
            else
                buffer.decode_unknown (wire_type);
        }

        if (buffer.read_index != end)
            buffer.error = true;
    }

    public size_t encode (Protobuf.EncodeBuffer buffer)
    {
        size_t n_written = 0;

        for (unowned List<FileDescriptorProto> i = this.file.last (); i != null; i = i.prev)
        {
            var file_length = i.data.encode (buffer);
            n_written += file_length;
            n_written += buffer.encode_varint (file_length);
            n_written += buffer.encode_varint (10);
        }

        return n_written;
    }

    public string to_string (string indent = "")
    {
        var text = "{\n";

        if (this.file != null)
        {
            text += "file = ";
            foreach (unowned FileDescriptorProto v in this.file)
                text += "%s;\n".printf (v.to_string ());
        }

        text += "}";
        return text;
    }
}

public class FileDescriptorProto
{
    public string name = "";
    public string package = "";
    public List<string> dependency = null;
    public List<DescriptorProto> message_type = null;
    public List<EnumDescriptorProto> enum_type = null;
    public List<ServiceDescriptorProto> service = null;
    public List<FieldDescriptorProto> extension = null;
    public FileOptions? options = null;
    public SourceCodeInfo? source_code_info = null;

    public FileDescriptorProto.from_data (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        decode (buffer, data_length);
    }

    public void decode (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        var end = buffer.read_index + data_length;

        while (buffer.read_index < end)
        {
            var key = buffer.decode_varint ();
            var wire_type = key & 0x7;
            var field_number = key >> 3;

            if (field_number == 1 && wire_type == 2)
                this.name = buffer.decode_string ((size_t) buffer.decode_varint ());
            else if (field_number == 2 && wire_type == 2)
                this.package = buffer.decode_string ((size_t) buffer.decode_varint ());
            else if (field_number == 3 && wire_type == 2)
                this.dependency.append (buffer.decode_string ((size_t) buffer.decode_varint ()));
            else if (field_number == 4 && wire_type == 2)
                this.message_type.append (new DescriptorProto.from_data (buffer, (size_t) buffer.decode_varint ()));
            else if (field_number == 5 && wire_type == 2)
                this.enum_type.append (new EnumDescriptorProto.from_data (buffer, (size_t) buffer.decode_varint ()));
            else if (field_number == 6 && wire_type == 2)
                this.service.append (new ServiceDescriptorProto.from_data (buffer, (size_t) buffer.decode_varint ()));
            else if (field_number == 7 && wire_type == 2)
                this.extension.append (new FieldDescriptorProto.from_data (buffer, (size_t) buffer.decode_varint ()));
            else if (field_number == 8 && wire_type == 2)
                this.options = new FileOptions.from_data (buffer, (size_t) buffer.decode_varint ());
            else if (field_number == 9 && wire_type == 2)
                this.source_code_info = new SourceCodeInfo.from_data (buffer, (size_t) buffer.decode_varint ());
            else
                buffer.decode_unknown (wire_type);
        }

        if (buffer.read_index != end)
            buffer.error = true;
    }

    public size_t encode (Protobuf.EncodeBuffer buffer)
    {
        size_t n_written = 0;

        if (this.source_code_info != null)
        {
            var source_code_info_length = this.source_code_info.encode (buffer);
            n_written += source_code_info_length;
            n_written += buffer.encode_varint (source_code_info_length);
            n_written += buffer.encode_varint (74);
        }
        if (this.options != null)
        {
            var options_length = this.options.encode (buffer);
            n_written += options_length;
            n_written += buffer.encode_varint (options_length);
            n_written += buffer.encode_varint (66);
        }
        for (unowned List<FieldDescriptorProto> i = this.extension.last (); i != null; i = i.prev)
        {
            var extension_length = i.data.encode (buffer);
            n_written += extension_length;
            n_written += buffer.encode_varint (extension_length);
            n_written += buffer.encode_varint (58);
        }
        for (unowned List<ServiceDescriptorProto> i = this.service.last (); i != null; i = i.prev)
        {
            var service_length = i.data.encode (buffer);
            n_written += service_length;
            n_written += buffer.encode_varint (service_length);
            n_written += buffer.encode_varint (50);
        }
        for (unowned List<EnumDescriptorProto> i = this.enum_type.last (); i != null; i = i.prev)
        {
            var enum_type_length = i.data.encode (buffer);
            n_written += enum_type_length;
            n_written += buffer.encode_varint (enum_type_length);
            n_written += buffer.encode_varint (42);
        }
        for (unowned List<DescriptorProto> i = this.message_type.last (); i != null; i = i.prev)
        {
            var message_type_length = i.data.encode (buffer);
            n_written += message_type_length;
            n_written += buffer.encode_varint (message_type_length);
            n_written += buffer.encode_varint (34);
        }
        for (unowned List<string> i = this.dependency.last (); i != null; i = i.prev)
        {
            var dependency_length = buffer.encode_string (i.data);
            n_written += dependency_length;
            n_written += buffer.encode_varint (dependency_length);
            n_written += buffer.encode_varint (26);
        }
        if (this.package != "")
        {
            var package_length = buffer.encode_string (this.package);
            n_written += package_length;
            n_written += buffer.encode_varint (package_length);
            n_written += buffer.encode_varint (18);
        }
        if (this.name != "")
        {
            var name_length = buffer.encode_string (this.name);
            n_written += name_length;
            n_written += buffer.encode_varint (name_length);
            n_written += buffer.encode_varint (10);
        }

        return n_written;
    }

    public string to_string (string indent = "")
    {
        var text = "{\n";

        if (this.name != "")
        {
            text += "name = ";
            text += "\"%s\";\n".printf (this.name);
        }

        if (this.package != "")
        {
            text += "package = ";
            text += "\"%s\";\n".printf (this.package);
        }

        if (this.dependency != null)
        {
            text += "dependency = ";
            foreach (unowned string v in this.dependency)
                text += "\"%s\";\n".printf (v);
        }

        if (this.message_type != null)
        {
            text += "message_type = ";
            foreach (unowned DescriptorProto v in this.message_type)
                text += "%s;\n".printf (v.to_string ());
        }

        if (this.enum_type != null)
        {
            text += "enum_type = ";
            foreach (unowned EnumDescriptorProto v in this.enum_type)
                text += "%s;\n".printf (v.to_string ());
        }

        if (this.service != null)
        {
            text += "service = ";
            foreach (unowned ServiceDescriptorProto v in this.service)
                text += "%s;\n".printf (v.to_string ());
        }

        if (this.extension != null)
        {
            text += "extension = ";
            foreach (unowned FieldDescriptorProto v in this.extension)
                text += "%s;\n".printf (v.to_string ());
        }

        if (this.options != null)
        {
            text += "options = ";
            text += "%s;\n".printf (this.options.to_string ());
        }

        if (this.source_code_info != null)
        {
            text += "source_code_info = ";
            text += "%s;\n".printf (this.source_code_info.to_string ());
        }

        text += "}";
        return text;
    }
}

public class DescriptorProto
{
    public class ExtensionRange
    {
        public int32 start = 0;
        public int32 end = 0;

        public ExtensionRange.from_data (Protobuf.DecodeBuffer buffer, size_t data_length)
        {
            decode (buffer, data_length);
        }

        public void decode (Protobuf.DecodeBuffer buffer, size_t data_length)
        {
            var end = buffer.read_index + data_length;

            while (buffer.read_index < end)
            {
                var key = buffer.decode_varint ();
                var wire_type = key & 0x7;
                var field_number = key >> 3;

                if (field_number == 1 && wire_type == 0)
                    this.start = buffer.decode_int32 ();
                else if (field_number == 2 && wire_type == 0)
                    this.end = buffer.decode_int32 ();
                else
                    buffer.decode_unknown (wire_type);
            }

            if (buffer.read_index != end)
                buffer.error = true;
        }

        public size_t encode (Protobuf.EncodeBuffer buffer)
        {
            size_t n_written = 0;

            if (this.end != 0)
            {
                n_written += buffer.encode_int32 (this.end);
                n_written += buffer.encode_varint (16);
            }
            if (this.start != 0)
            {
                n_written += buffer.encode_int32 (this.start);
                n_written += buffer.encode_varint (8);
            }

            return n_written;
        }

        public string to_string (string indent = "")
        {
            var text = "{\n";

            if (this.start != 0)
            {
                text += "start = ";
                text += "%s;\n".printf (this.start.to_string ());
            }

            if (this.end != 0)
            {
                text += "end = ";
                text += "%s;\n".printf (this.end.to_string ());
            }

            text += "}";
            return text;
        }
    }
    public string name = "";
    public List<FieldDescriptorProto> field = null;
    public List<FieldDescriptorProto> extension = null;
    public List<DescriptorProto> nested_type = null;
    public List<EnumDescriptorProto> enum_type = null;
    public List<ExtensionRange> extension_range = null;
    public MessageOptions? options = null;

    public DescriptorProto.from_data (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        decode (buffer, data_length);
    }

    public void decode (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        var end = buffer.read_index + data_length;

        while (buffer.read_index < end)
        {
            var key = buffer.decode_varint ();
            var wire_type = key & 0x7;
            var field_number = key >> 3;

            if (field_number == 1 && wire_type == 2)
                this.name = buffer.decode_string ((size_t) buffer.decode_varint ());
            else if (field_number == 2 && wire_type == 2)
                this.field.append (new FieldDescriptorProto.from_data (buffer, (size_t) buffer.decode_varint ()));
            else if (field_number == 6 && wire_type == 2)
                this.extension.append (new FieldDescriptorProto.from_data (buffer, (size_t) buffer.decode_varint ()));
            else if (field_number == 3 && wire_type == 2)
                this.nested_type.append (new DescriptorProto.from_data (buffer, (size_t) buffer.decode_varint ()));
            else if (field_number == 4 && wire_type == 2)
                this.enum_type.append (new EnumDescriptorProto.from_data (buffer, (size_t) buffer.decode_varint ()));
            else if (field_number == 5 && wire_type == 2)
                this.extension_range.append (new ExtensionRange.from_data (buffer, (size_t) buffer.decode_varint ()));
            else if (field_number == 7 && wire_type == 2)
                this.options = new MessageOptions.from_data (buffer, (size_t) buffer.decode_varint ());
            else
                buffer.decode_unknown (wire_type);
        }

        if (buffer.read_index != end)
            buffer.error = true;
    }

    public size_t encode (Protobuf.EncodeBuffer buffer)
    {
        size_t n_written = 0;

        if (this.options != null)
        {
            var options_length = this.options.encode (buffer);
            n_written += options_length;
            n_written += buffer.encode_varint (options_length);
            n_written += buffer.encode_varint (58);
        }
        for (unowned List<ExtensionRange> i = this.extension_range.last (); i != null; i = i.prev)
        {
            var extension_range_length = i.data.encode (buffer);
            n_written += extension_range_length;
            n_written += buffer.encode_varint (extension_range_length);
            n_written += buffer.encode_varint (42);
        }
        for (unowned List<EnumDescriptorProto> i = this.enum_type.last (); i != null; i = i.prev)
        {
            var enum_type_length = i.data.encode (buffer);
            n_written += enum_type_length;
            n_written += buffer.encode_varint (enum_type_length);
            n_written += buffer.encode_varint (34);
        }
        for (unowned List<DescriptorProto> i = this.nested_type.last (); i != null; i = i.prev)
        {
            var nested_type_length = i.data.encode (buffer);
            n_written += nested_type_length;
            n_written += buffer.encode_varint (nested_type_length);
            n_written += buffer.encode_varint (26);
        }
        for (unowned List<FieldDescriptorProto> i = this.extension.last (); i != null; i = i.prev)
        {
            var extension_length = i.data.encode (buffer);
            n_written += extension_length;
            n_written += buffer.encode_varint (extension_length);
            n_written += buffer.encode_varint (50);
        }
        for (unowned List<FieldDescriptorProto> i = this.field.last (); i != null; i = i.prev)
        {
            var field_length = i.data.encode (buffer);
            n_written += field_length;
            n_written += buffer.encode_varint (field_length);
            n_written += buffer.encode_varint (18);
        }
        if (this.name != "")
        {
            var name_length = buffer.encode_string (this.name);
            n_written += name_length;
            n_written += buffer.encode_varint (name_length);
            n_written += buffer.encode_varint (10);
        }

        return n_written;
    }

    public string to_string (string indent = "")
    {
        var text = "{\n";

        if (this.name != "")
        {
            text += "name = ";
            text += "\"%s\";\n".printf (this.name);
        }

        if (this.field != null)
        {
            text += "field = ";
            foreach (unowned FieldDescriptorProto v in this.field)
                text += "%s;\n".printf (v.to_string ());
        }

        if (this.extension != null)
        {
            text += "extension = ";
            foreach (unowned FieldDescriptorProto v in this.extension)
                text += "%s;\n".printf (v.to_string ());
        }

        if (this.nested_type != null)
        {
            text += "nested_type = ";
            foreach (unowned DescriptorProto v in this.nested_type)
                text += "%s;\n".printf (v.to_string ());
        }

        if (this.enum_type != null)
        {
            text += "enum_type = ";
            foreach (unowned EnumDescriptorProto v in this.enum_type)
                text += "%s;\n".printf (v.to_string ());
        }

        if (this.extension_range != null)
        {
            text += "extension_range = ";
            foreach (unowned ExtensionRange v in this.extension_range)
                text += "%s;\n".printf (v.to_string ());
        }

        if (this.options != null)
        {
            text += "options = ";
            text += "%s;\n".printf (this.options.to_string ());
        }

        text += "}";
        return text;
    }
}

public class FieldDescriptorProto
{
    public enum Type
    {
        TYPE_DOUBLE = 1,
        TYPE_FLOAT = 2,
        TYPE_INT64 = 3,
        TYPE_UINT64 = 4,
        TYPE_INT32 = 5,
        TYPE_FIXED64 = 6,
        TYPE_FIXED32 = 7,
        TYPE_BOOL = 8,
        TYPE_STRING = 9,
        TYPE_GROUP = 10,
        TYPE_MESSAGE = 11,
        TYPE_BYTES = 12,
        TYPE_UINT32 = 13,
        TYPE_ENUM = 14,
        TYPE_SFIXED32 = 15,
        TYPE_SFIXED64 = 16,
        TYPE_SINT32 = 17,
        TYPE_SINT64 = 18,
    }
    public enum Label
    {
        LABEL_OPTIONAL = 1,
        LABEL_REQUIRED = 2,
        LABEL_REPEATED = 3,
    }
    public string name = "";
    public int32 number = 0;
    public Label label = 0;
    public Type type = 0;
    public string type_name = "";
    public string extendee = "";
    public string default_value = "";
    public FieldOptions? options = null;

    public FieldDescriptorProto.from_data (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        decode (buffer, data_length);
    }

    public void decode (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        var end = buffer.read_index + data_length;

        while (buffer.read_index < end)
        {
            var key = buffer.decode_varint ();
            var wire_type = key & 0x7;
            var field_number = key >> 3;

            if (field_number == 1 && wire_type == 2)
                this.name = buffer.decode_string ((size_t) buffer.decode_varint ());
            else if (field_number == 3 && wire_type == 0)
                this.number = buffer.decode_int32 ();
            else if (field_number == 4 && wire_type == 0)
                this.label = (Label) buffer.decode_varint ();
            else if (field_number == 5 && wire_type == 0)
                this.type = (Type) buffer.decode_varint ();
            else if (field_number == 6 && wire_type == 2)
                this.type_name = buffer.decode_string ((size_t) buffer.decode_varint ());
            else if (field_number == 2 && wire_type == 2)
                this.extendee = buffer.decode_string ((size_t) buffer.decode_varint ());
            else if (field_number == 7 && wire_type == 2)
                this.default_value = buffer.decode_string ((size_t) buffer.decode_varint ());
            else if (field_number == 8 && wire_type == 2)
                this.options = new FieldOptions.from_data (buffer, (size_t) buffer.decode_varint ());
            else
                buffer.decode_unknown (wire_type);
        }

        if (buffer.read_index != end)
            buffer.error = true;
    }

    public size_t encode (Protobuf.EncodeBuffer buffer)
    {
        size_t n_written = 0;

        if (this.options != null)
        {
            var options_length = this.options.encode (buffer);
            n_written += options_length;
            n_written += buffer.encode_varint (options_length);
            n_written += buffer.encode_varint (66);
        }
        if (this.default_value != "")
        {
            var default_value_length = buffer.encode_string (this.default_value);
            n_written += default_value_length;
            n_written += buffer.encode_varint (default_value_length);
            n_written += buffer.encode_varint (58);
        }
        if (this.extendee != "")
        {
            var extendee_length = buffer.encode_string (this.extendee);
            n_written += extendee_length;
            n_written += buffer.encode_varint (extendee_length);
            n_written += buffer.encode_varint (18);
        }
        if (this.type_name != "")
        {
            var type_name_length = buffer.encode_string (this.type_name);
            n_written += type_name_length;
            n_written += buffer.encode_varint (type_name_length);
            n_written += buffer.encode_varint (50);
        }
        if (this.type != 0)
        {
            n_written += buffer.encode_varint (this.type);
            n_written += buffer.encode_varint (40);
        }
        if (this.label != 0)
        {
            n_written += buffer.encode_varint (this.label);
            n_written += buffer.encode_varint (32);
        }
        if (this.number != 0)
        {
            n_written += buffer.encode_int32 (this.number);
            n_written += buffer.encode_varint (24);
        }
        if (this.name != "")
        {
            var name_length = buffer.encode_string (this.name);
            n_written += name_length;
            n_written += buffer.encode_varint (name_length);
            n_written += buffer.encode_varint (10);
        }

        return n_written;
    }

    public string to_string (string indent = "")
    {
        var text = "{\n";

        if (this.name != "")
        {
            text += "name = ";
            text += "\"%s\";\n".printf (this.name);
        }

        if (this.number != 0)
        {
            text += "number = ";
            text += "%s;\n".printf (this.number.to_string ());
        }

        if (this.label != 0)
        {
            text += "label = ";
            text += "%s;\n".printf (this.label.to_string ());
        }

        if (this.type != 0)
        {
            text += "type = ";
            text += "%s;\n".printf (this.type.to_string ());
        }

        if (this.type_name != "")
        {
            text += "type_name = ";
            text += "\"%s\";\n".printf (this.type_name);
        }

        if (this.extendee != "")
        {
            text += "extendee = ";
            text += "\"%s\";\n".printf (this.extendee);
        }

        if (this.default_value != "")
        {
            text += "default_value = ";
            text += "\"%s\";\n".printf (this.default_value);
        }

        if (this.options != null)
        {
            text += "options = ";
            text += "%s;\n".printf (this.options.to_string ());
        }

        text += "}";
        return text;
    }
}

public class EnumDescriptorProto
{
    public string name = "";
    public List<EnumValueDescriptorProto> value = null;
    public EnumOptions? options = null;

    public EnumDescriptorProto.from_data (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        decode (buffer, data_length);
    }

    public void decode (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        var end = buffer.read_index + data_length;

        while (buffer.read_index < end)
        {
            var key = buffer.decode_varint ();
            var wire_type = key & 0x7;
            var field_number = key >> 3;

            if (field_number == 1 && wire_type == 2)
                this.name = buffer.decode_string ((size_t) buffer.decode_varint ());
            else if (field_number == 2 && wire_type == 2)
                this.value.append (new EnumValueDescriptorProto.from_data (buffer, (size_t) buffer.decode_varint ()));
            else if (field_number == 3 && wire_type == 2)
                this.options = new EnumOptions.from_data (buffer, (size_t) buffer.decode_varint ());
            else
                buffer.decode_unknown (wire_type);
        }

        if (buffer.read_index != end)
            buffer.error = true;
    }

    public size_t encode (Protobuf.EncodeBuffer buffer)
    {
        size_t n_written = 0;

        if (this.options != null)
        {
            var options_length = this.options.encode (buffer);
            n_written += options_length;
            n_written += buffer.encode_varint (options_length);
            n_written += buffer.encode_varint (26);
        }
        for (unowned List<EnumValueDescriptorProto> i = this.value.last (); i != null; i = i.prev)
        {
            var value_length = i.data.encode (buffer);
            n_written += value_length;
            n_written += buffer.encode_varint (value_length);
            n_written += buffer.encode_varint (18);
        }
        if (this.name != "")
        {
            var name_length = buffer.encode_string (this.name);
            n_written += name_length;
            n_written += buffer.encode_varint (name_length);
            n_written += buffer.encode_varint (10);
        }

        return n_written;
    }

    public string to_string (string indent = "")
    {
        var text = "{\n";

        if (this.name != "")
        {
            text += "name = ";
            text += "\"%s\";\n".printf (this.name);
        }

        if (this.value != null)
        {
            text += "value = ";
            foreach (unowned EnumValueDescriptorProto v in this.value)
                text += "%s;\n".printf (v.to_string ());
        }

        if (this.options != null)
        {
            text += "options = ";
            text += "%s;\n".printf (this.options.to_string ());
        }

        text += "}";
        return text;
    }
}

public class EnumValueDescriptorProto
{
    public string name = "";
    public int32 number = 0;
    public EnumValueOptions? options = null;

    public EnumValueDescriptorProto.from_data (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        decode (buffer, data_length);
    }

    public void decode (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        var end = buffer.read_index + data_length;

        while (buffer.read_index < end)
        {
            var key = buffer.decode_varint ();
            var wire_type = key & 0x7;
            var field_number = key >> 3;

            if (field_number == 1 && wire_type == 2)
                this.name = buffer.decode_string ((size_t) buffer.decode_varint ());
            else if (field_number == 2 && wire_type == 0)
                this.number = buffer.decode_int32 ();
            else if (field_number == 3 && wire_type == 2)
                this.options = new EnumValueOptions.from_data (buffer, (size_t) buffer.decode_varint ());
            else
                buffer.decode_unknown (wire_type);
        }

        if (buffer.read_index != end)
            buffer.error = true;
    }

    public size_t encode (Protobuf.EncodeBuffer buffer)
    {
        size_t n_written = 0;

        if (this.options != null)
        {
            var options_length = this.options.encode (buffer);
            n_written += options_length;
            n_written += buffer.encode_varint (options_length);
            n_written += buffer.encode_varint (26);
        }
        if (this.number != 0)
        {
            n_written += buffer.encode_int32 (this.number);
            n_written += buffer.encode_varint (16);
        }
        if (this.name != "")
        {
            var name_length = buffer.encode_string (this.name);
            n_written += name_length;
            n_written += buffer.encode_varint (name_length);
            n_written += buffer.encode_varint (10);
        }

        return n_written;
    }

    public string to_string (string indent = "")
    {
        var text = "{\n";

        if (this.name != "")
        {
            text += "name = ";
            text += "\"%s\";\n".printf (this.name);
        }

        if (this.number != 0)
        {
            text += "number = ";
            text += "%s;\n".printf (this.number.to_string ());
        }

        if (this.options != null)
        {
            text += "options = ";
            text += "%s;\n".printf (this.options.to_string ());
        }

        text += "}";
        return text;
    }
}

public class ServiceDescriptorProto
{
    public string name = "";
    public List<MethodDescriptorProto> method = null;
    public ServiceOptions? options = null;

    public ServiceDescriptorProto.from_data (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        decode (buffer, data_length);
    }

    public void decode (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        var end = buffer.read_index + data_length;

        while (buffer.read_index < end)
        {
            var key = buffer.decode_varint ();
            var wire_type = key & 0x7;
            var field_number = key >> 3;

            if (field_number == 1 && wire_type == 2)
                this.name = buffer.decode_string ((size_t) buffer.decode_varint ());
            else if (field_number == 2 && wire_type == 2)
                this.method.append (new MethodDescriptorProto.from_data (buffer, (size_t) buffer.decode_varint ()));
            else if (field_number == 3 && wire_type == 2)
                this.options = new ServiceOptions.from_data (buffer, (size_t) buffer.decode_varint ());
            else
                buffer.decode_unknown (wire_type);
        }

        if (buffer.read_index != end)
            buffer.error = true;
    }

    public size_t encode (Protobuf.EncodeBuffer buffer)
    {
        size_t n_written = 0;

        if (this.options != null)
        {
            var options_length = this.options.encode (buffer);
            n_written += options_length;
            n_written += buffer.encode_varint (options_length);
            n_written += buffer.encode_varint (26);
        }
        for (unowned List<MethodDescriptorProto> i = this.method.last (); i != null; i = i.prev)
        {
            var method_length = i.data.encode (buffer);
            n_written += method_length;
            n_written += buffer.encode_varint (method_length);
            n_written += buffer.encode_varint (18);
        }
        if (this.name != "")
        {
            var name_length = buffer.encode_string (this.name);
            n_written += name_length;
            n_written += buffer.encode_varint (name_length);
            n_written += buffer.encode_varint (10);
        }

        return n_written;
    }

    public string to_string (string indent = "")
    {
        var text = "{\n";

        if (this.name != "")
        {
            text += "name = ";
            text += "\"%s\";\n".printf (this.name);
        }

        if (this.method != null)
        {
            text += "method = ";
            foreach (unowned MethodDescriptorProto v in this.method)
                text += "%s;\n".printf (v.to_string ());
        }

        if (this.options != null)
        {
            text += "options = ";
            text += "%s;\n".printf (this.options.to_string ());
        }

        text += "}";
        return text;
    }
}

public class MethodDescriptorProto
{
    public string name = "";
    public string input_type = "";
    public string output_type = "";
    public MethodOptions? options = null;

    public MethodDescriptorProto.from_data (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        decode (buffer, data_length);
    }

    public void decode (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        var end = buffer.read_index + data_length;

        while (buffer.read_index < end)
        {
            var key = buffer.decode_varint ();
            var wire_type = key & 0x7;
            var field_number = key >> 3;

            if (field_number == 1 && wire_type == 2)
                this.name = buffer.decode_string ((size_t) buffer.decode_varint ());
            else if (field_number == 2 && wire_type == 2)
                this.input_type = buffer.decode_string ((size_t) buffer.decode_varint ());
            else if (field_number == 3 && wire_type == 2)
                this.output_type = buffer.decode_string ((size_t) buffer.decode_varint ());
            else if (field_number == 4 && wire_type == 2)
                this.options = new MethodOptions.from_data (buffer, (size_t) buffer.decode_varint ());
            else
                buffer.decode_unknown (wire_type);
        }

        if (buffer.read_index != end)
            buffer.error = true;
    }

    public size_t encode (Protobuf.EncodeBuffer buffer)
    {
        size_t n_written = 0;

        if (this.options != null)
        {
            var options_length = this.options.encode (buffer);
            n_written += options_length;
            n_written += buffer.encode_varint (options_length);
            n_written += buffer.encode_varint (34);
        }
        if (this.output_type != "")
        {
            var output_type_length = buffer.encode_string (this.output_type);
            n_written += output_type_length;
            n_written += buffer.encode_varint (output_type_length);
            n_written += buffer.encode_varint (26);
        }
        if (this.input_type != "")
        {
            var input_type_length = buffer.encode_string (this.input_type);
            n_written += input_type_length;
            n_written += buffer.encode_varint (input_type_length);
            n_written += buffer.encode_varint (18);
        }
        if (this.name != "")
        {
            var name_length = buffer.encode_string (this.name);
            n_written += name_length;
            n_written += buffer.encode_varint (name_length);
            n_written += buffer.encode_varint (10);
        }

        return n_written;
    }

    public string to_string (string indent = "")
    {
        var text = "{\n";

        if (this.name != "")
        {
            text += "name = ";
            text += "\"%s\";\n".printf (this.name);
        }

        if (this.input_type != "")
        {
            text += "input_type = ";
            text += "\"%s\";\n".printf (this.input_type);
        }

        if (this.output_type != "")
        {
            text += "output_type = ";
            text += "\"%s\";\n".printf (this.output_type);
        }

        if (this.options != null)
        {
            text += "options = ";
            text += "%s;\n".printf (this.options.to_string ());
        }

        text += "}";
        return text;
    }
}

public class FileOptions
{
    public enum OptimizeMode
    {
        SPEED = 1,
        CODE_SIZE = 2,
        LITE_RUNTIME = 3,
    }
    public string java_package = "";
    public string java_outer_classname = "";
    public bool java_multiple_files = false;
    public bool java_generate_equals_and_hash = false;
    public OptimizeMode optimize_for = 0;
    public bool cc_generic_services = false;
    public bool java_generic_services = false;
    public bool py_generic_services = false;
    public List<UninterpretedOption> uninterpreted_option = null;

    public FileOptions.from_data (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        decode (buffer, data_length);
    }

    public void decode (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        var end = buffer.read_index + data_length;

        while (buffer.read_index < end)
        {
            var key = buffer.decode_varint ();
            var wire_type = key & 0x7;
            var field_number = key >> 3;

            if (field_number == 1 && wire_type == 2)
                this.java_package = buffer.decode_string ((size_t) buffer.decode_varint ());
            else if (field_number == 8 && wire_type == 2)
                this.java_outer_classname = buffer.decode_string ((size_t) buffer.decode_varint ());
            else if (field_number == 10 && wire_type == 0)
                this.java_multiple_files = buffer.decode_bool ();
            else if (field_number == 20 && wire_type == 0)
                this.java_generate_equals_and_hash = buffer.decode_bool ();
            else if (field_number == 9 && wire_type == 0)
                this.optimize_for = (OptimizeMode) buffer.decode_varint ();
            else if (field_number == 16 && wire_type == 0)
                this.cc_generic_services = buffer.decode_bool ();
            else if (field_number == 17 && wire_type == 0)
                this.java_generic_services = buffer.decode_bool ();
            else if (field_number == 18 && wire_type == 0)
                this.py_generic_services = buffer.decode_bool ();
            else if (field_number == 999 && wire_type == 2)
                this.uninterpreted_option.append (new UninterpretedOption.from_data (buffer, (size_t) buffer.decode_varint ()));
            else
                buffer.decode_unknown (wire_type);
        }

        if (buffer.read_index != end)
            buffer.error = true;
    }

    public size_t encode (Protobuf.EncodeBuffer buffer)
    {
        size_t n_written = 0;

        for (unowned List<UninterpretedOption> i = this.uninterpreted_option.last (); i != null; i = i.prev)
        {
            var uninterpreted_option_length = i.data.encode (buffer);
            n_written += uninterpreted_option_length;
            n_written += buffer.encode_varint (uninterpreted_option_length);
            n_written += buffer.encode_varint (7994);
        }
        if (this.py_generic_services != false)
        {
            n_written += buffer.encode_bool (this.py_generic_services);
            n_written += buffer.encode_varint (144);
        }
        if (this.java_generic_services != false)
        {
            n_written += buffer.encode_bool (this.java_generic_services);
            n_written += buffer.encode_varint (136);
        }
        if (this.cc_generic_services != false)
        {
            n_written += buffer.encode_bool (this.cc_generic_services);
            n_written += buffer.encode_varint (128);
        }
        if (this.optimize_for != 0)
        {
            n_written += buffer.encode_varint (this.optimize_for);
            n_written += buffer.encode_varint (72);
        }
        if (this.java_generate_equals_and_hash != false)
        {
            n_written += buffer.encode_bool (this.java_generate_equals_and_hash);
            n_written += buffer.encode_varint (160);
        }
        if (this.java_multiple_files != false)
        {
            n_written += buffer.encode_bool (this.java_multiple_files);
            n_written += buffer.encode_varint (80);
        }
        if (this.java_outer_classname != "")
        {
            var java_outer_classname_length = buffer.encode_string (this.java_outer_classname);
            n_written += java_outer_classname_length;
            n_written += buffer.encode_varint (java_outer_classname_length);
            n_written += buffer.encode_varint (66);
        }
        if (this.java_package != "")
        {
            var java_package_length = buffer.encode_string (this.java_package);
            n_written += java_package_length;
            n_written += buffer.encode_varint (java_package_length);
            n_written += buffer.encode_varint (10);
        }

        return n_written;
    }

    public string to_string (string indent = "")
    {
        var text = "{\n";

        if (this.java_package != "")
        {
            text += "java_package = ";
            text += "\"%s\";\n".printf (this.java_package);
        }

        if (this.java_outer_classname != "")
        {
            text += "java_outer_classname = ";
            text += "\"%s\";\n".printf (this.java_outer_classname);
        }

        if (this.java_multiple_files != false)
        {
            text += "java_multiple_files = ";
            text += "%s;\n".printf (this.java_multiple_files.to_string ());
        }

        if (this.java_generate_equals_and_hash != false)
        {
            text += "java_generate_equals_and_hash = ";
            text += "%s;\n".printf (this.java_generate_equals_and_hash.to_string ());
        }

        if (this.optimize_for != 0)
        {
            text += "optimize_for = ";
            text += "%s;\n".printf (this.optimize_for.to_string ());
        }

        if (this.cc_generic_services != false)
        {
            text += "cc_generic_services = ";
            text += "%s;\n".printf (this.cc_generic_services.to_string ());
        }

        if (this.java_generic_services != false)
        {
            text += "java_generic_services = ";
            text += "%s;\n".printf (this.java_generic_services.to_string ());
        }

        if (this.py_generic_services != false)
        {
            text += "py_generic_services = ";
            text += "%s;\n".printf (this.py_generic_services.to_string ());
        }

        if (this.uninterpreted_option != null)
        {
            text += "uninterpreted_option = ";
            foreach (unowned UninterpretedOption v in this.uninterpreted_option)
                text += "%s;\n".printf (v.to_string ());
        }

        text += "}";
        return text;
    }
}

public class MessageOptions
{
    public bool message_set_wire_format = false;
    public bool no_standard_descriptor_accessor = false;
    public List<UninterpretedOption> uninterpreted_option = null;

    public MessageOptions.from_data (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        decode (buffer, data_length);
    }

    public void decode (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        var end = buffer.read_index + data_length;

        while (buffer.read_index < end)
        {
            var key = buffer.decode_varint ();
            var wire_type = key & 0x7;
            var field_number = key >> 3;

            if (field_number == 1 && wire_type == 0)
                this.message_set_wire_format = buffer.decode_bool ();
            else if (field_number == 2 && wire_type == 0)
                this.no_standard_descriptor_accessor = buffer.decode_bool ();
            else if (field_number == 999 && wire_type == 2)
                this.uninterpreted_option.append (new UninterpretedOption.from_data (buffer, (size_t) buffer.decode_varint ()));
            else
                buffer.decode_unknown (wire_type);
        }

        if (buffer.read_index != end)
            buffer.error = true;
    }

    public size_t encode (Protobuf.EncodeBuffer buffer)
    {
        size_t n_written = 0;

        for (unowned List<UninterpretedOption> i = this.uninterpreted_option.last (); i != null; i = i.prev)
        {
            var uninterpreted_option_length = i.data.encode (buffer);
            n_written += uninterpreted_option_length;
            n_written += buffer.encode_varint (uninterpreted_option_length);
            n_written += buffer.encode_varint (7994);
        }
        if (this.no_standard_descriptor_accessor != false)
        {
            n_written += buffer.encode_bool (this.no_standard_descriptor_accessor);
            n_written += buffer.encode_varint (16);
        }
        if (this.message_set_wire_format != false)
        {
            n_written += buffer.encode_bool (this.message_set_wire_format);
            n_written += buffer.encode_varint (8);
        }

        return n_written;
    }

    public string to_string (string indent = "")
    {
        var text = "{\n";

        if (this.message_set_wire_format != false)
        {
            text += "message_set_wire_format = ";
            text += "%s;\n".printf (this.message_set_wire_format.to_string ());
        }

        if (this.no_standard_descriptor_accessor != false)
        {
            text += "no_standard_descriptor_accessor = ";
            text += "%s;\n".printf (this.no_standard_descriptor_accessor.to_string ());
        }

        if (this.uninterpreted_option != null)
        {
            text += "uninterpreted_option = ";
            foreach (unowned UninterpretedOption v in this.uninterpreted_option)
                text += "%s;\n".printf (v.to_string ());
        }

        text += "}";
        return text;
    }
}

public class FieldOptions
{
    public enum CType
    {
        STRING = 0,
        CORD = 1,
        STRING_PIECE = 2,
    }
    public CType ctype = 0;
    public bool packed = false;
    public bool deprecated = false;
    public string experimental_map_key = "";
    public List<UninterpretedOption> uninterpreted_option = null;

    public FieldOptions.from_data (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        decode (buffer, data_length);
    }

    public void decode (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        var end = buffer.read_index + data_length;

        while (buffer.read_index < end)
        {
            var key = buffer.decode_varint ();
            var wire_type = key & 0x7;
            var field_number = key >> 3;

            if (field_number == 1 && wire_type == 0)
                this.ctype = (CType) buffer.decode_varint ();
            else if (field_number == 2 && wire_type == 0)
                this.packed = buffer.decode_bool ();
            else if (field_number == 3 && wire_type == 0)
                this.deprecated = buffer.decode_bool ();
            else if (field_number == 9 && wire_type == 2)
                this.experimental_map_key = buffer.decode_string ((size_t) buffer.decode_varint ());
            else if (field_number == 999 && wire_type == 2)
                this.uninterpreted_option.append (new UninterpretedOption.from_data (buffer, (size_t) buffer.decode_varint ()));
            else
                buffer.decode_unknown (wire_type);
        }

        if (buffer.read_index != end)
            buffer.error = true;
    }

    public size_t encode (Protobuf.EncodeBuffer buffer)
    {
        size_t n_written = 0;

        for (unowned List<UninterpretedOption> i = this.uninterpreted_option.last (); i != null; i = i.prev)
        {
            var uninterpreted_option_length = i.data.encode (buffer);
            n_written += uninterpreted_option_length;
            n_written += buffer.encode_varint (uninterpreted_option_length);
            n_written += buffer.encode_varint (7994);
        }
        if (this.experimental_map_key != "")
        {
            var experimental_map_key_length = buffer.encode_string (this.experimental_map_key);
            n_written += experimental_map_key_length;
            n_written += buffer.encode_varint (experimental_map_key_length);
            n_written += buffer.encode_varint (74);
        }
        if (this.deprecated != false)
        {
            n_written += buffer.encode_bool (this.deprecated);
            n_written += buffer.encode_varint (24);
        }
        if (this.packed != false)
        {
            n_written += buffer.encode_bool (this.packed);
            n_written += buffer.encode_varint (16);
        }
        if (this.ctype != 0)
        {
            n_written += buffer.encode_varint (this.ctype);
            n_written += buffer.encode_varint (8);
        }

        return n_written;
    }

    public string to_string (string indent = "")
    {
        var text = "{\n";

        if (this.ctype != 0)
        {
            text += "ctype = ";
            text += "%s;\n".printf (this.ctype.to_string ());
        }

        if (this.packed != false)
        {
            text += "packed = ";
            text += "%s;\n".printf (this.packed.to_string ());
        }

        if (this.deprecated != false)
        {
            text += "deprecated = ";
            text += "%s;\n".printf (this.deprecated.to_string ());
        }

        if (this.experimental_map_key != "")
        {
            text += "experimental_map_key = ";
            text += "\"%s\";\n".printf (this.experimental_map_key);
        }

        if (this.uninterpreted_option != null)
        {
            text += "uninterpreted_option = ";
            foreach (unowned UninterpretedOption v in this.uninterpreted_option)
                text += "%s;\n".printf (v.to_string ());
        }

        text += "}";
        return text;
    }
}

public class EnumOptions
{
    public List<UninterpretedOption> uninterpreted_option = null;

    public EnumOptions.from_data (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        decode (buffer, data_length);
    }

    public void decode (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        var end = buffer.read_index + data_length;

        while (buffer.read_index < end)
        {
            var key = buffer.decode_varint ();
            var wire_type = key & 0x7;
            var field_number = key >> 3;

            if (field_number == 999 && wire_type == 2)
                this.uninterpreted_option.append (new UninterpretedOption.from_data (buffer, (size_t) buffer.decode_varint ()));
            else
                buffer.decode_unknown (wire_type);
        }

        if (buffer.read_index != end)
            buffer.error = true;
    }

    public size_t encode (Protobuf.EncodeBuffer buffer)
    {
        size_t n_written = 0;

        for (unowned List<UninterpretedOption> i = this.uninterpreted_option.last (); i != null; i = i.prev)
        {
            var uninterpreted_option_length = i.data.encode (buffer);
            n_written += uninterpreted_option_length;
            n_written += buffer.encode_varint (uninterpreted_option_length);
            n_written += buffer.encode_varint (7994);
        }

        return n_written;
    }

    public string to_string (string indent = "")
    {
        var text = "{\n";

        if (this.uninterpreted_option != null)
        {
            text += "uninterpreted_option = ";
            foreach (unowned UninterpretedOption v in this.uninterpreted_option)
                text += "%s;\n".printf (v.to_string ());
        }

        text += "}";
        return text;
    }
}

public class EnumValueOptions
{
    public List<UninterpretedOption> uninterpreted_option = null;

    public EnumValueOptions.from_data (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        decode (buffer, data_length);
    }

    public void decode (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        var end = buffer.read_index + data_length;

        while (buffer.read_index < end)
        {
            var key = buffer.decode_varint ();
            var wire_type = key & 0x7;
            var field_number = key >> 3;

            if (field_number == 999 && wire_type == 2)
                this.uninterpreted_option.append (new UninterpretedOption.from_data (buffer, (size_t) buffer.decode_varint ()));
            else
                buffer.decode_unknown (wire_type);
        }

        if (buffer.read_index != end)
            buffer.error = true;
    }

    public size_t encode (Protobuf.EncodeBuffer buffer)
    {
        size_t n_written = 0;

        for (unowned List<UninterpretedOption> i = this.uninterpreted_option.last (); i != null; i = i.prev)
        {
            var uninterpreted_option_length = i.data.encode (buffer);
            n_written += uninterpreted_option_length;
            n_written += buffer.encode_varint (uninterpreted_option_length);
            n_written += buffer.encode_varint (7994);
        }

        return n_written;
    }

    public string to_string (string indent = "")
    {
        var text = "{\n";

        if (this.uninterpreted_option != null)
        {
            text += "uninterpreted_option = ";
            foreach (unowned UninterpretedOption v in this.uninterpreted_option)
                text += "%s;\n".printf (v.to_string ());
        }

        text += "}";
        return text;
    }
}

public class ServiceOptions
{
    public List<UninterpretedOption> uninterpreted_option = null;

    public ServiceOptions.from_data (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        decode (buffer, data_length);
    }

    public void decode (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        var end = buffer.read_index + data_length;

        while (buffer.read_index < end)
        {
            var key = buffer.decode_varint ();
            var wire_type = key & 0x7;
            var field_number = key >> 3;

            if (field_number == 999 && wire_type == 2)
                this.uninterpreted_option.append (new UninterpretedOption.from_data (buffer, (size_t) buffer.decode_varint ()));
            else
                buffer.decode_unknown (wire_type);
        }

        if (buffer.read_index != end)
            buffer.error = true;
    }

    public size_t encode (Protobuf.EncodeBuffer buffer)
    {
        size_t n_written = 0;

        for (unowned List<UninterpretedOption> i = this.uninterpreted_option.last (); i != null; i = i.prev)
        {
            var uninterpreted_option_length = i.data.encode (buffer);
            n_written += uninterpreted_option_length;
            n_written += buffer.encode_varint (uninterpreted_option_length);
            n_written += buffer.encode_varint (7994);
        }

        return n_written;
    }

    public string to_string (string indent = "")
    {
        var text = "{\n";

        if (this.uninterpreted_option != null)
        {
            text += "uninterpreted_option = ";
            foreach (unowned UninterpretedOption v in this.uninterpreted_option)
                text += "%s;\n".printf (v.to_string ());
        }

        text += "}";
        return text;
    }
}

public class MethodOptions
{
    public List<UninterpretedOption> uninterpreted_option = null;

    public MethodOptions.from_data (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        decode (buffer, data_length);
    }

    public void decode (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        var end = buffer.read_index + data_length;

        while (buffer.read_index < end)
        {
            var key = buffer.decode_varint ();
            var wire_type = key & 0x7;
            var field_number = key >> 3;

            if (field_number == 999 && wire_type == 2)
                this.uninterpreted_option.append (new UninterpretedOption.from_data (buffer, (size_t) buffer.decode_varint ()));
            else
                buffer.decode_unknown (wire_type);
        }

        if (buffer.read_index != end)
            buffer.error = true;
    }

    public size_t encode (Protobuf.EncodeBuffer buffer)
    {
        size_t n_written = 0;

        for (unowned List<UninterpretedOption> i = this.uninterpreted_option.last (); i != null; i = i.prev)
        {
            var uninterpreted_option_length = i.data.encode (buffer);
            n_written += uninterpreted_option_length;
            n_written += buffer.encode_varint (uninterpreted_option_length);
            n_written += buffer.encode_varint (7994);
        }

        return n_written;
    }

    public string to_string (string indent = "")
    {
        var text = "{\n";

        if (this.uninterpreted_option != null)
        {
            text += "uninterpreted_option = ";
            foreach (unowned UninterpretedOption v in this.uninterpreted_option)
                text += "%s;\n".printf (v.to_string ());
        }

        text += "}";
        return text;
    }
}

public class UninterpretedOption
{
    public class NamePart
    {
        public string name_part = "";
        public bool is_extension = false;

        public NamePart.from_data (Protobuf.DecodeBuffer buffer, size_t data_length)
        {
            decode (buffer, data_length);
        }

        public void decode (Protobuf.DecodeBuffer buffer, size_t data_length)
        {
            var end = buffer.read_index + data_length;
            var have_name_part = false;
            var have_is_extension = false;

            while (buffer.read_index < end)
            {
                var key = buffer.decode_varint ();
                var wire_type = key & 0x7;
                var field_number = key >> 3;

                if (field_number == 1 && wire_type == 2)
                {
                    this.name_part = buffer.decode_string ((size_t) buffer.decode_varint ());
                    have_name_part = true;
                }
                else if (field_number == 2 && wire_type == 0)
                {
                    this.is_extension = buffer.decode_bool ();
                    have_is_extension = true;
                }
                else
                    buffer.decode_unknown (wire_type);
            }

            if (buffer.read_index != end)
                buffer.error = true;
            else if (!have_name_part || !have_is_extension)
                buffer.error = true;
        }

        public size_t encode (Protobuf.EncodeBuffer buffer)
        {
            size_t n_written = 0;

            n_written += buffer.encode_bool (this.is_extension);
            n_written += buffer.encode_varint (16);
            var name_part_length = buffer.encode_string (this.name_part);
            n_written += name_part_length;
            n_written += buffer.encode_varint (name_part_length);
            n_written += buffer.encode_varint (10);

            return n_written;
        }

        public string to_string (string indent = "")
        {
            var text = "{\n";

            text += "name_part = ";
            text += "\"%s\";\n".printf (this.name_part);

            text += "is_extension = ";
            text += "%s;\n".printf (this.is_extension.to_string ());

            text += "}";
            return text;
        }
    }
    public List<NamePart> name = null;
    public string identifier_value = "";
    public uint64 positive_int_value = 0;
    public int64 negative_int_value = 0;
    public double double_value = 0d;
    public GLib.ByteArray string_value = null;
    public string aggregate_value = "";

    public UninterpretedOption.from_data (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        decode (buffer, data_length);
    }

    public void decode (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        var end = buffer.read_index + data_length;

        while (buffer.read_index < end)
        {
            var key = buffer.decode_varint ();
            var wire_type = key & 0x7;
            var field_number = key >> 3;

            if (field_number == 2 && wire_type == 2)
                this.name.append (new NamePart.from_data (buffer, (size_t) buffer.decode_varint ()));
            else if (field_number == 3 && wire_type == 2)
                this.identifier_value = buffer.decode_string ((size_t) buffer.decode_varint ());
            else if (field_number == 4 && wire_type == 0)
                this.positive_int_value = buffer.decode_uint64 ();
            else if (field_number == 5 && wire_type == 0)
                this.negative_int_value = buffer.decode_int64 ();
            else if (field_number == 6 && wire_type == 1)
                this.double_value = buffer.decode_double ();
            else if (field_number == 7 && wire_type == 2)
                this.string_value = buffer.decode_bytes ((size_t) buffer.decode_varint ());
            else if (field_number == 8 && wire_type == 2)
                this.aggregate_value = buffer.decode_string ((size_t) buffer.decode_varint ());
            else
                buffer.decode_unknown (wire_type);
        }

        if (buffer.read_index != end)
            buffer.error = true;
    }

    public size_t encode (Protobuf.EncodeBuffer buffer)
    {
        size_t n_written = 0;

        if (this.aggregate_value != "")
        {
            var aggregate_value_length = buffer.encode_string (this.aggregate_value);
            n_written += aggregate_value_length;
            n_written += buffer.encode_varint (aggregate_value_length);
            n_written += buffer.encode_varint (66);
        }
        if (this.string_value != null)
        {
            var string_value_length = buffer.encode_bytes (this.string_value);
            n_written += string_value_length;
            n_written += buffer.encode_varint (string_value_length);
            n_written += buffer.encode_varint (58);
        }
        if (this.double_value != 0d)
        {
            n_written += buffer.encode_double (this.double_value);
            n_written += buffer.encode_varint (48);
        }
        if (this.negative_int_value != 0)
        {
            n_written += buffer.encode_int64 (this.negative_int_value);
            n_written += buffer.encode_varint (40);
        }
        if (this.positive_int_value != 0)
        {
            n_written += buffer.encode_uint64 (this.positive_int_value);
            n_written += buffer.encode_varint (32);
        }
        if (this.identifier_value != "")
        {
            var identifier_value_length = buffer.encode_string (this.identifier_value);
            n_written += identifier_value_length;
            n_written += buffer.encode_varint (identifier_value_length);
            n_written += buffer.encode_varint (26);
        }
        for (unowned List<NamePart> i = this.name.last (); i != null; i = i.prev)
        {
            var name_length = i.data.encode (buffer);
            n_written += name_length;
            n_written += buffer.encode_varint (name_length);
            n_written += buffer.encode_varint (18);
        }

        return n_written;
    }

    public string to_string (string indent = "")
    {
        var text = "{\n";

        if (this.name != null)
        {
            text += "name = ";
            foreach (unowned NamePart v in this.name)
                text += "%s;\n".printf (v.to_string ());
        }

        if (this.identifier_value != "")
        {
            text += "identifier_value = ";
            text += "\"%s\";\n".printf (this.identifier_value);
        }

        if (this.positive_int_value != 0)
        {
            text += "positive_int_value = ";
            text += "%s;\n".printf (this.positive_int_value.to_string ());
        }

        if (this.negative_int_value != 0)
        {
            text += "negative_int_value = ";
            text += "%s;\n".printf (this.negative_int_value.to_string ());
        }

        if (this.double_value != 0d)
        {
            text += "double_value = ";
            text += "%s;\n".printf (this.double_value.to_string ());
        }

        if (this.string_value != null)
        {
            text += "string_value = ";
            for (var i = 0; i < this.string_value.len; i++)
                text += "%02X".printf (this.string_value.data[i]);
            text += "\n";
        }

        if (this.aggregate_value != "")
        {
            text += "aggregate_value = ";
            text += "\"%s\";\n".printf (this.aggregate_value);
        }

        text += "}";
        return text;
    }
}

public class SourceCodeInfo
{
    public class Location
    {
        public List<int32> path = null;
        public List<int32> span = null;

        public Location.from_data (Protobuf.DecodeBuffer buffer, size_t data_length)
        {
            decode (buffer, data_length);
        }

        public void decode (Protobuf.DecodeBuffer buffer, size_t data_length)
        {
            var end = buffer.read_index + data_length;

            while (buffer.read_index < end)
            {
                var key = buffer.decode_varint ();
                var wire_type = key & 0x7;
                var field_number = key >> 3;

                if (field_number == 1 && wire_type == 0)
                    this.path.append (buffer.decode_int32 ());
                else if (field_number == 2 && wire_type == 0)
                    this.span.append (buffer.decode_int32 ());
                else
                    buffer.decode_unknown (wire_type);
            }

            if (buffer.read_index != end)
                buffer.error = true;
        }

        public size_t encode (Protobuf.EncodeBuffer buffer)
        {
            size_t n_written = 0;

            for (unowned List<int32> i = this.span.last (); i != null; i = i.prev)
            {
                n_written += buffer.encode_int32 (i.data);
                n_written += buffer.encode_varint (16);
            }
            for (unowned List<int32> i = this.path.last (); i != null; i = i.prev)
            {
                n_written += buffer.encode_int32 (i.data);
                n_written += buffer.encode_varint (8);
            }

            return n_written;
        }

        public string to_string (string indent = "")
        {
            var text = "{\n";

            if (this.path != null)
            {
                text += "path = ";
                foreach (unowned int32 v in this.path)
                    text += "%s;\n".printf (v.to_string ());
            }

            if (this.span != null)
            {
                text += "span = ";
                foreach (unowned int32 v in this.span)
                    text += "%s;\n".printf (v.to_string ());
            }

            text += "}";
            return text;
        }
    }
    public List<Location> location = null;

    public SourceCodeInfo.from_data (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        decode (buffer, data_length);
    }

    public void decode (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        var end = buffer.read_index + data_length;

        while (buffer.read_index < end)
        {
            var key = buffer.decode_varint ();
            var wire_type = key & 0x7;
            var field_number = key >> 3;

            if (field_number == 1 && wire_type == 2)
                this.location.append (new Location.from_data (buffer, (size_t) buffer.decode_varint ()));
            else
                buffer.decode_unknown (wire_type);
        }

        if (buffer.read_index != end)
            buffer.error = true;
    }

    public size_t encode (Protobuf.EncodeBuffer buffer)
    {
        size_t n_written = 0;

        for (unowned List<Location> i = this.location.last (); i != null; i = i.prev)
        {
            var location_length = i.data.encode (buffer);
            n_written += location_length;
            n_written += buffer.encode_varint (location_length);
            n_written += buffer.encode_varint (10);
        }

        return n_written;
    }

    public string to_string (string indent = "")
    {
        var text = "{\n";

        if (this.location != null)
        {
            text += "location = ";
            foreach (unowned Location v in this.location)
                text += "%s;\n".printf (v.to_string ());
        }

        text += "}";
        return text;
    }
}
