// Generated by protoc-gen-vala 0.0.5 from plugin.proto, do not edit

public class CodeGeneratorRequest
{
    public List<string> file_to_generate = null;
    public string parameter = "";
    public List<FileDescriptorProto> proto_file = null;

    public CodeGeneratorRequest.from_data (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        decode (buffer, data_length);
    }

    public void decode (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        var end = buffer.read_index + data_length;

        while (buffer.read_index < end)
        {
            var key = buffer.decode_varint ();
            var wire_type = key & 0x7;
            var field_number = key >> 3;

            if (field_number == 1 && wire_type == 2)
                this.file_to_generate.append (buffer.decode_string ((size_t) buffer.decode_varint ()));
            else if (field_number == 2 && wire_type == 2)
                this.parameter = buffer.decode_string ((size_t) buffer.decode_varint ());
            else if (field_number == 15 && wire_type == 2)
                this.proto_file.append (new FileDescriptorProto.from_data (buffer, (size_t) buffer.decode_varint ()));
            else
                buffer.decode_unknown (wire_type);
        }

        if (buffer.read_index != end)
            buffer.error = true;
    }

    public size_t encode (Protobuf.EncodeBuffer buffer)
    {
        size_t n_written = 0;

        for (unowned List<FileDescriptorProto> i = this.proto_file.last (); i != null; i = i.prev)
        {
            var proto_file_length = i.data.encode (buffer);
            n_written += proto_file_length;
            n_written += buffer.encode_varint (proto_file_length);
            n_written += buffer.encode_varint (122);
        }
        if (this.parameter != "")
        {
            var parameter_length = buffer.encode_string (this.parameter);
            n_written += parameter_length;
            n_written += buffer.encode_varint (parameter_length);
            n_written += buffer.encode_varint (18);
        }
        for (unowned List<string> i = this.file_to_generate.last (); i != null; i = i.prev)
        {
            var file_to_generate_length = buffer.encode_string (i.data);
            n_written += file_to_generate_length;
            n_written += buffer.encode_varint (file_to_generate_length);
            n_written += buffer.encode_varint (10);
        }

        return n_written;
    }

    public string to_string (string indent = "")
    {
        var text = "{\n";

        text += indent + "    file_to_generate =\n";
        text += indent + "    [\n";
        foreach (unowned string v in this.file_to_generate)
            text += indent + "        %s,\n".printf (Protobuf.string_to_string (v));
        text += indent + "    ];\n";

        text += indent + "    parameter = %s;\n".printf (Protobuf.string_to_string (this.parameter));
        text += indent + "    proto_file =\n";
        text += indent + "    [\n";
        foreach (unowned FileDescriptorProto v in this.proto_file)
            text += indent + "        %s,\n".printf (v.to_string (indent + "        "));
        text += indent + "    ];\n";


        text += indent + "}";

        return text;
    }
}

public class CodeGeneratorResponse
{
    public class File
    {
        public string name = "";
        public string insertion_point = "";
        public string content = "";

        public File.from_data (Protobuf.DecodeBuffer buffer, size_t data_length)
        {
            decode (buffer, data_length);
        }

        public void decode (Protobuf.DecodeBuffer buffer, size_t data_length)
        {
            var end = buffer.read_index + data_length;

            while (buffer.read_index < end)
            {
                var key = buffer.decode_varint ();
                var wire_type = key & 0x7;
                var field_number = key >> 3;

                if (field_number == 1 && wire_type == 2)
                    this.name = buffer.decode_string ((size_t) buffer.decode_varint ());
                else if (field_number == 2 && wire_type == 2)
                    this.insertion_point = buffer.decode_string ((size_t) buffer.decode_varint ());
                else if (field_number == 15 && wire_type == 2)
                    this.content = buffer.decode_string ((size_t) buffer.decode_varint ());
                else
                    buffer.decode_unknown (wire_type);
            }

            if (buffer.read_index != end)
                buffer.error = true;
        }

        public size_t encode (Protobuf.EncodeBuffer buffer)
        {
            size_t n_written = 0;

            if (this.content != "")
            {
                var content_length = buffer.encode_string (this.content);
                n_written += content_length;
                n_written += buffer.encode_varint (content_length);
                n_written += buffer.encode_varint (122);
            }
            if (this.insertion_point != "")
            {
                var insertion_point_length = buffer.encode_string (this.insertion_point);
                n_written += insertion_point_length;
                n_written += buffer.encode_varint (insertion_point_length);
                n_written += buffer.encode_varint (18);
            }
            if (this.name != "")
            {
                var name_length = buffer.encode_string (this.name);
                n_written += name_length;
                n_written += buffer.encode_varint (name_length);
                n_written += buffer.encode_varint (10);
            }

            return n_written;
        }

        public string to_string (string indent = "")
        {
            var text = "{\n";

            text += indent + "    name = %s;\n".printf (Protobuf.string_to_string (this.name));
            text += indent + "    insertion_point = %s;\n".printf (Protobuf.string_to_string (this.insertion_point));
            text += indent + "    content = %s;\n".printf (Protobuf.string_to_string (this.content));

            text += indent + "}";

            return text;
        }
    }
    public string error = "";
    public List<File> file = null;

    public CodeGeneratorResponse.from_data (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        decode (buffer, data_length);
    }

    public void decode (Protobuf.DecodeBuffer buffer, size_t data_length)
    {
        var end = buffer.read_index + data_length;

        while (buffer.read_index < end)
        {
            var key = buffer.decode_varint ();
            var wire_type = key & 0x7;
            var field_number = key >> 3;

            if (field_number == 1 && wire_type == 2)
                this.error = buffer.decode_string ((size_t) buffer.decode_varint ());
            else if (field_number == 15 && wire_type == 2)
                this.file.append (new File.from_data (buffer, (size_t) buffer.decode_varint ()));
            else
                buffer.decode_unknown (wire_type);
        }

        if (buffer.read_index != end)
            buffer.error = true;
    }

    public size_t encode (Protobuf.EncodeBuffer buffer)
    {
        size_t n_written = 0;

        for (unowned List<File> i = this.file.last (); i != null; i = i.prev)
        {
            var file_length = i.data.encode (buffer);
            n_written += file_length;
            n_written += buffer.encode_varint (file_length);
            n_written += buffer.encode_varint (122);
        }
        if (this.error != "")
        {
            var error_length = buffer.encode_string (this.error);
            n_written += error_length;
            n_written += buffer.encode_varint (error_length);
            n_written += buffer.encode_varint (10);
        }

        return n_written;
    }

    public string to_string (string indent = "")
    {
        var text = "{\n";

        text += indent + "    error = %s;\n".printf (Protobuf.string_to_string (this.error));
        text += indent + "    file =\n";
        text += indent + "    [\n";
        foreach (unowned File v in this.file)
            text += indent + "        %s,\n".printf (v.to_string (indent + "        "));
        text += indent + "    ];\n";


        text += indent + "}";

        return text;
    }
}
